apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinelist-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/deivisondelmiro/cinelist
    targetRevision: main
    path: helm/app
    helm:
      valueFiles:
      - values-prod.yaml
      parameters:
      - name: global.environment
        value: "prod"
  destination:
    server: https://kubernetes.default.svc
    namespace: cinelist-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  ignoreDifferences:
  - group: batch
    kind: Job
    jsonPointers:
    - /metadata/annotations
    - /status